version: '2'

services:
  php:
    build: ./docker/php
    volumes:
        - ./src:/var/www/html
        - ./conf/php/php-dev.ini:/usr/local/etc/php/php.ini
        - ./conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
  web:
    image: nginx:latest
    volumes:
        - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./src:/var/www/html
    ports:
        - "8181:80"

  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - TZ=Europe/Paris

  pma:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 1337:80
    environment:
      - TZ=Europe/Paris
      - PMA_USER=root
      - PMA_PASSWORD=root

  test:
    image: node:6.2
    working_dir: /test
    volumes:
      - ./test:/test
    depends_on:
      - php
      - web
      - db
    environment:
      - TZ=Europe/Paris